grid_map_filters:
    # Duplicate layer.
  - name: duplicate_z
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: z
      output_layer: z_finite

  # Fill holes in the map with inpainting.
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: z
      output_layer: z_inpainted
      radius: 0.4

  # Reduce noise with a radial blurring filter.
  - name: mean_in_radius
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: z_inpainted
      output_layer: z_smooth
      radius: 0.2

  # Compute surface normals.
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: z_inpainted
      output_layers_prefix: normal_vectors_
      radius: 0.15
      normal_vector_positive_axis: z

  # Compute smooth surface normals.
  - name: smooth_surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: z_smooth
      output_layers_prefix: smooth_normal_vectors_
      radius: 0.4
      normal_vector_positive_axis: z

  # Add a color layer for visualization based on the surface normal.
  - name: normal_color_map
    type: gridMapFilters/NormalColorMapFilter
    params:
      input_layers_prefix: normal_vectors_
      output_layer: normal_color

  # Compute slope from surface normal.
  - name: slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope
      expression: acos(normal_vectors_z)

  # Compute roughness as absolute difference from map to smoothened map.
  - name: roughness
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: roughness
      expression: abs(z_inpainted - z_smooth)

  # # Uncomment to use edges
  # # Edge detection by computing the standard deviation from slope.
  # - name: edge_detection
  #   type: gridMapFilters/SlidingWindowMathExpressionFilter
  #   params:
  #     input_layer: slope
  #     output_layer: edges
  #     expression: sqrt(sumOfFinites(square(slope - meanOfFinites(slope))) ./ numberOfFinites(slope)) # Standard deviation
  #     compute_empty_cells: false
  #     edge_handling: crop # options: inside, crop, empty, mean
  #     window_length: 0.2

  # Compute traversability as normalized weighted sum of slope and roughness.
  - name: traversability
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability_raw
      expression: 0.5 * (1.0 - (slope / 0.3)) + 0.5 * (1.0 - (roughness / 0.4))

  #   # Compute traversability as normalized weighted sum of slope and roughness.
  # - name: traversability_user_mask
  #   type: gridMapFilters/MathExpressionFilter
  #   params:
  #     output_layer: traversability
  #     expression: ( (0.5 - 0.5 * (x - 3.0) ./ (sqrt((x - 3.0).^2))) + 
  #                   (0.5 + 0.5 * (x - 3.2) ./ (sqrt((x - 3.2).^2))) + 
  #                   (0.5 - 0.5 * (y + 1.0) ./ (sqrt((y + 1.0).^2))) + 
  #                   (0.5 + 0.5 * (y - 1.0) ./ (sqrt((y - 1.0).^2))))
  #                 .* traversability

  # Set lower threshold on traversability.
  - name: z_finite_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: z
      output_layer: z_finite
      lower_threshold: -1000.0
      set_to: -1000.0

  # Compute traversability as normalized weighted sum of slope and roughness.
  - name: traversability_user_mask
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability_raw
      expression: (1 - abs(z_finite - z_inpainted)) .* traversability_raw

  - name: traversability_filter
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: traversability_raw
      output_layer: traversability
      radius: 0.05

  # Delete layers.
  - name: delete
    type: gridMapFilters/DeletionFilter
    params:
      layers: [traversability_raw, z_finite]

  # Set lower threshold on traversability.
  - name: traversability_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability
      output_layer: traversability
      lower_threshold: 0.0
      set_to: 0.0

  # Set upper threshold on traversability.
  - name: traversability_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability
      output_layer: traversability
      upper_threshold: 1.0
      set_to: 1.0 # Other uses: .nan, .inf

  # Duplicate layer.
  - name: duplicate
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: traversability
      output_layer: traversability_mask

  # Set lower threshold on traversability.
  - name: traversability_mask_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability_mask
      output_layer: traversability_mask
      lower_threshold: 0.6 # Note - for now must match /local_footstep_planner/foothold_obj_threshold
      set_to: 0.0
