sudo: required

notifications:
  email:
    recipients:
    - nflowers@andrew.cmu.edu
    on_success: always
    on_failure: always

branches:
  only:
  - master

addons:
  apt:
    packages:
    - doxygen
language: generic

matrix:
  include:
  - os: linux
    arch: amd64
    name: 18.04 Melodic
    dist: bionic
    env: ROS_DISTRO=melodic
  - os: linux
    arch: arm64
    name: 18.04 Melodic
    dist: bionic
    env: ROS_DISTRO=melodic

env:
  global:
  - CI_SOURCE_PATH=$(pwd)
  - ROS_PARALLEL_JOBS='-j8 -l6'
  - secure: uV0Csk4OKk0bpv6BYJyi3wjlvO0KPgmeATQaL6XWlTzzkh58M24R7jRBVobDfXkrrofsC5rIAKAx+BJcNB1BeLEZ4FWceG5/uFF9FU81ugLZT1ZdkDvnL6pFHhGHYVg8ZAF8XQxHCxaCK99p8XkKqE+/DJSn1x//l7CtKJPFvqI+lvXR6xn4LubyTp0yrGodX2wi6zyk2Mvv0hLERvupWYuo9JC7a/M1mt53AL7VcmFiLpwV59XGOEaj6BZEAA53DhaVdvDp+boB5H4tvH7ENKEolqRdQwnlnDLqsi9oNuEz1WMou8/AX+QBl8i2yRgemHqdnMEUef/YzoUSCemquRCzLlSqk9WvOG77KxfNMcKkYCAKFIDJFaUsGutDWBb2tUELixIOiti4kUFK9z+SMJEnc/NEc27LIGlxpexDG55HFgjVBO3RyFHPZRrjh9AwH0bLKyi717QaBWfyCedk125Qx4CTfizAf596puYbal+7qhCgOSEY3rNFHEjQ7Y9jCAnjoVIOvI7rmxNJUWnZN4b/9j3CNEDBBzvqw60AY06+UAsVwXQYY0gef/E8tKugAtoe536sFM/lBX1A9B0un/IRcHTEgbalSQgYR0llLnPNkLwFXoxwWbM4FhkDWM8bEk+G/IM8VIiLsAivCe0Fzr/V7pcPgg3BEGFOKSq5ABY=

before_install:
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main">
  /etc/apt/sources.list.d/ros-latest.list'
- sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
- sudo apt update
- sudo apt install doxygen
- sudo apt install -y python-rosdep python-rosinstall python-rosinstall-generator
  python-wstool build-essential
- sudo apt install -y ros-$ROS_DISTRO-ros-base
- source /opt/ros/$ROS_DISTRO/setup.bash
- sudo rosdep init
- rosdep update

install:
- mkdir -p ~/catkin_ws/src
- ln -s $CI_SOURCE_PATH ~/catkin_ws/src/
- cd $TRAVIS_BUILD_DIR
- chmod +x setup.sh
- ./setup.sh
- source /opt/ros/$ROS_DISTRO/setup.bash
- cd ~/catkin_ws
- catkin_make
- source devel/setup.bash

before_script:
- roscore &
- sleep 5

script:
- cd ~/catkin_ws
- catkin_make run_tests && catkin_test_results

before_deploy:
- cd $TRAVIS_BUILD_DIR
- doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: docs/
  on:
    branch: master
