axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.5
  y: 0.25
scale_linear_turbo:
  x: 1.0
  y: 0.5
axis_angular:
  yaw: 2
scale_angular:
  yaw: 1.0
scale_angular_turbo:
  yaw: 1.0
enable_button: 8
enable_turbo_button: 7
stand_button: 1
sit_button: 2
safety_button: 3
